import { _electron as electron } from 'playwright';
import assert from 'node:assert/strict';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { clampBounds } from '../dist-electron/geometry.js';
mkdirSync('evidence', { recursive: true });
const checks = [];
const check = (name, ok) => { assert.ok(ok, name); checks.push(name); console.log(`PASS ${name}`); };
const app = await electron.launch({ args: ['.', '--verify'], cwd: process.cwd() });
try {
 const page = await app.firstWindow();
 // Keep the existing single-card detail/dismissal checks; default-stack behavior has its own acceptance script.
 const openSingleDemo = async () => {
  await page.getByRole('button', { name: '打开通知，2 条未读示例' }).click();
  await page.getByRole('button', { name: '展开 2 条通知' }).click();
  await page.getByRole('button', { name: '标记你设定的提醒已查看' }).click();
  await page.waitForFunction(() => document.querySelectorAll('.result').length === 1);
 };
 await page.evaluate(() => localStorage.clear());
 await page.reload();
 const errors = []; page.on('pageerror', error => errors.push(error.message));
 await page.evaluate(() => { window.__feedbackEvents = []; window.addEventListener('jarvis:feedback', e => window.__feedbackEvents.push(e.detail)); });
 const audioEvents = () => page.evaluate(() => window.__feedbackEvents);
 await page.waitForSelector('.voice-pill');
 await page.waitForTimeout(400);
 check('launch does not play a feedback sound', (await audioEvents()).length === 0);
 const state = () => app.evaluate(({ BrowserWindow, screen }) => { const w = BrowserWindow.getAllWindows()[0]; return { bounds: w.getBounds(), visible: w.isVisible(), focused: w.isFocused(), focusable: w.isFocusable(), alwaysOnTop: w.isAlwaysOnTop(), allSpaces: w.isVisibleOnAllWorkspaces(), displays: screen.getAllDisplays().map(d => ({ id: d.id, workArea: d.workArea })), preferences: w.webContents.getLastWebPreferences() }; });
 let native = await state();
 check('desktop launches inactive and always on top', !native.focused && !native.focusable && native.alwaysOnTop);
 check('renderer uses sandbox and isolated context', native.preferences.sandbox && native.preferences.contextIsolation && !native.preferences.nodeIntegration);
 check('center renders a quiet living waveform', await page.locator('.voice-presence').getAttribute('data-state') === 'standby');
 const visibleGroup = () => page.evaluate(() => { const a = document.querySelector('.entry-surface').getBoundingClientRect(), b = document.querySelector('.notification').getBoundingClientRect(); return { width: b.right-a.left, height: a.height, center: (a.left+b.right)/2 }; });
 const voiceGroup = await visibleGroup();
 check('voice surfaces occupy 270 by 40 logical pixels', voiceGroup.width === 270 && voiceGroup.height === 40);
 await page.getByRole('button', { name: '关闭麦克风（模拟）', exact: true }).hover();
 await page.waitForTimeout(180);
 check('microphone hover appears inside the capsule', await page.locator('.edge-control').first().evaluate(e => Number(getComputedStyle(e, '::after').opacity) > .08));
 await page.screenshot({ path: 'evidence/01-voice.png', omitBackground: true });
 await page.getByRole('button', { name: '关闭麦克风（模拟）', exact: true }).click();
 await page.waitForFunction(() => window.__feedbackEvents.at(-1)?.cue === 'mic-off');
 await page.getByRole('button', { name: '关闭播报声音', exact: true }).click();
 await page.waitForFunction(() => window.__feedbackEvents.at(-1)?.cue === 'speaker-off');
 check('microphone and playback mute independently', await page.getByRole('button', { name: '开启麦克风（模拟）' }).getAttribute('aria-pressed') === 'true' && await page.getByRole('button', { name: '开启播报声音' }).getAttribute('aria-pressed') === 'true');
 await page.getByRole('button', { name: '开启麦克风（模拟）' }).click();
 await page.waitForFunction(() => window.__feedbackEvents.at(-1)?.cue === 'mic-on');
 check('mute actions play distinct reference feedback cues', (await audioEvents()).map(e => e.cue).join(',') === 'mic-off,speaker-off,mic-on');
 check('enabling microphone preserves playback mute', await page.getByRole('button', { name: '开启播报声音' }).count() === 1);
 await openSingleDemo();
 await page.waitForSelector('.result');
 await page.waitForTimeout(220);
 const cardGap = await page.evaluate(() => document.querySelector('.result').getBoundingClientRect().top - document.querySelector('.voice-pill').getBoundingClientRect().bottom);
 check('notification sits 12 pixels below the capsule', Math.abs(cardGap - 12) < .5);
 check('notification expands below controls', await page.locator('.result').count() === 1 && (await page.locator('.result').boundingBox()).y > (await page.locator('.control-row').boundingBox()).y);
 check('notification does not acquire native focus', !(await state()).focused);
 await page.screenshot({ path: 'evidence/02-inbox.png', omitBackground: true });
 await page.locator('.voice-pill').click({ button: 'right' });
 await page.waitForSelector('.settings');
 check('right-click opens settings while notifications stay visible', await page.locator('.result').count() === 1);
 await page.waitForTimeout(220);
 check('settings and notification fit inside the native window', (await page.locator('.inbox').boundingBox()).y + (await page.locator('.inbox').boundingBox()).height < (await state()).bounds.height);
 await page.screenshot({ path: 'evidence/05-settings.png', omitBackground: true });
 await page.getByRole('slider', { name: '玻璃不透明度' }).press('Escape');
 check('Escape closes settings and releases native focus', await page.locator('.settings').count() === 0 && !(await state()).focusable);
 await page.locator('.result-main').click();
 await page.getByRole('button', { name: '复制', exact: true }).click();
 await page.getByRole('button', { name: '已复制', exact: true }).waitFor();
 check('detail copies actual sample content', (await app.evaluate(({ clipboard }) => clipboard.readText())).includes('未进行真实查询'));
 await page.screenshot({ path: 'evidence/03-detail.png', omitBackground: true });
 await page.getByRole('button', { name: '关闭结果详情' }).click();
 check('closing detail releases native focus', !(await state()).focusable);
 await page.evaluate(() => {
  window.__fadeSamples = [];
  const inbox = document.querySelector('.inbox');
  const observer = new MutationObserver(() => {
   if (!inbox.classList.contains('is-closing')) return;
   observer.disconnect();
   const start = performance.now();
   const sample = () => {
    window.__fadeSamples.push({ ms: performance.now() - start, opacity: Number(getComputedStyle(inbox).opacity), attached: inbox.isConnected });
    if (inbox.isConnected && performance.now() - start < 300) requestAnimationFrame(sample);
   };
   sample();
  });
  observer.observe(inbox, { attributes: true, attributeFilter: ['class'] });
 });
 await page.getByRole('button', { name: '收起通知' }).click();
 await page.waitForTimeout(230);
 const fade = await page.evaluate(() => window.__fadeSamples);
 writeFileSync('evidence/notification-fade.json', JSON.stringify(fade, null, 2));
 check('notification fades before its surface is removed', fade.some(v => v.opacity > .05 && v.opacity < .95) && fade.at(-1).attached === false);
 await page.getByRole('button', { name: '展开文字输入' }).click();
 await page.waitForTimeout(350);
 const textGroup = await visibleGroup();
 check('text expands to 330 pixels around the same center', textGroup.width === 330 && textGroup.center === voiceGroup.center);
 check('text mode receives native and input focus', (await state()).focusable && await page.getByRole('textbox').evaluate(e => document.activeElement === e));
 await page.getByRole('textbox').fill('记一下：下次我们一起设计中间的声纹。');
 await page.getByRole('button', { name: '添加内容', exact: true }).click();
 await page.getByRole('button', { name: '附加示例便笺' }).click();
 check('attachment is explicitly simulated', (await page.locator('.attachment').innerText()).includes('示例便笺'));
 await page.screenshot({ path: 'evidence/04-text.png', omitBackground: true });
 await page.getByRole('button', { name: '发送示例输入' }).click();
 check('sending enters processing without creating notification', (await page.locator('[role=status]').innerText()).includes('正在处理'));
 await page.waitForSelector('.reply');
 check('reply explicitly states simulation', (await page.locator('.reply').innerText()).includes('没有保存或执行真实任务'));
 await page.getByRole('button', { name: '停止播报', exact: true }).click();
 check('interrupt returns to listening', (await page.locator('[role=status]').innerText()).includes('正在听取'));
 await page.getByRole('textbox').fill('长文本检查。'.repeat(600));
 check('long input remains complete', (await page.getByRole('textbox').inputValue()).length === 3600);
 await page.getByRole('textbox').press('Escape');
 await page.getByRole('button', { name: '外观与窗口选项' }).click();
 await page.getByRole('slider', { name: '玻璃不透明度' }).fill('0.5');
 check('opacity setting updates material overlay', await page.getByRole('slider', { name: '玻璃不透明度' }).inputValue() === '0.5');
 await page.getByRole('slider', { name: '毛玻璃强度' }).fill('0.6');
 check('blur strength and opacity adjust independently', await page.locator('main').evaluate(e => e.style.getPropertyValue('--glass-strength') === '0.6' && e.style.getPropertyValue('--glass-opacity') === '0.5'));
 await page.getByRole('switch', { name: '操作提示音' }).click();
 const beforeSilentClick = (await audioEvents()).length;
 await page.getByRole('button', { name: '关闭麦克风（模拟）', exact: true }).click();
 await page.waitForTimeout(80);
 check('feedback switch silences clicks without blocking microphone state', (await audioEvents()).length === beforeSilentClick && await page.getByRole('button', { name: '开启麦克风（模拟）' }).count() === 1);
 await page.getByRole('button', { name: '开启麦克风（模拟）' }).click();
 check('appearance and feedback preferences are stored', await page.evaluate(() => { const p = JSON.parse(localStorage.getItem('resonance-appearance-v1')); return p.opacity === .5 && p.glassStrength === .6 && p.feedbackEnabled === false; }));
 await page.getByRole('button', { name: '恢复默认' }).click();
 check('opacity default restores', await page.getByRole('slider', { name: '玻璃不透明度' }).inputValue() === '0.4');
 await page.getByRole('button', { name: '关闭外观设置' }).click();
 const clamp = clampBounds({ x: -1900, y: 1100, width: 604, height: 300 }, { x: -1600, y: 0, width: 1600, height: 900 });
 check('negative-origin display boundaries clamp correctly', clamp.x === -1600 && clamp.y === 600);
 await app.evaluate(({ BrowserWindow }) => { const w = BrowserWindow.getAllWindows()[0]; w.setPosition(-9000, -9000); });
 await page.waitForTimeout(300);
 native = await state();
 check('native moved window is recovered inside a display', native.displays.some(d => native.bounds.x >= d.workArea.x && native.bounds.y >= d.workArea.y));
 await page.getByRole('button', { name: '结束语音并隐藏胶囊' }).focus();
 check('end control is keyboard accessible', await page.getByRole('button', { name: '结束语音并隐藏胶囊' }).evaluate(e => document.activeElement === e));
 await page.getByRole('button', { name: '结束语音并隐藏胶囊' }).press('Enter');
 await page.waitForTimeout(200);
 check('ending voice hides window', !(await state()).visible);
 await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].showInactive());
 check('restoring ended voice returns to idle', await page.getByRole('button', { name: '开始语音演示' }).count() === 1);
 check('ending voice preserves task result', await page.getByRole('button', { name: '打开通知，0 条未读示例' }).count() === 1);
 await page.getByRole('button', { name: '开始语音演示' }).click();
 await page.waitForFunction(() => window.__feedbackEvents.at(-1)?.cue === 'voice-enter');
 check('starting voice plays the entry cue', (await audioEvents()).at(-1).duration > .5);
 await page.getByRole('button', { name: '开启播报声音' }).click();
 await page.waitForFunction(() => window.__feedbackEvents.at(-1)?.cue === 'speaker-on');
 check('enabling playback has its own cue', (await audioEvents()).at(-1).cue === 'speaker-on');
 await page.getByRole('button', { name: '外观与窗口选项' }).click();
 await page.getByRole('button', { name: '隐藏浮窗', exact: true }).click();
 await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].showInactive());
 check('hiding preserves voice mode', await page.locator('.shell.mode-voice .voice-presence').count() === 1);
 await page.emulateMedia({ reducedMotion: 'reduce' });
 check('reduced motion disables transitions', await page.locator('.icon-button').first().evaluate(e => getComputedStyle(e).transitionDuration) === '0s');
 await page.getByRole('slider', { name: '玻璃不透明度' }).fill('0.52');
 await page.getByRole('slider', { name: '毛玻璃强度' }).fill('0.42');
 await page.reload();
 await page.waitForSelector('.voice-pill');
 await page.getByRole('button', { name: '外观与窗口选项' }).click();
 check('appearance survives an actual renderer reload', await page.getByRole('slider', { name: '玻璃不透明度' }).inputValue() === '0.52' && await page.getByRole('slider', { name: '毛玻璃强度' }).inputValue() === '0.42');
 await page.getByRole('button', { name: '恢复默认' }).click();
 await page.getByRole('button', { name: '关闭外观设置' }).click();
 await page.emulateMedia({ reducedMotion: 'no-preference' });
 await openSingleDemo();
 await page.waitForTimeout(220);
 await page.getByRole('button', { name: '收起通知' }).click();
 await page.waitForTimeout(40);
 await page.getByRole('button', { name: '打开通知，1 条未读示例' }).click();
 await page.waitForTimeout(220);
 check('reopening during fade preserves one complete notification', await page.locator('.result').count() === 1 && await page.locator('.inbox').evaluate(e => Number(getComputedStyle(e).opacity) === 1));
 await page.evaluate(() => {
  window.__dismissSamples = [];
  const card = document.querySelector('.result');
  const observer = new MutationObserver(() => {
   if (!card.classList.contains('is-dismissing')) return;
   observer.disconnect();
   const start = performance.now();
   const sample = () => {
    window.__dismissSamples.push({ ms: performance.now()-start, height: card.getBoundingClientRect().height, opacity: Number(getComputedStyle(card).opacity), attached: card.isConnected });
    if (card.isConnected && performance.now()-start < 300) requestAnimationFrame(sample);
   };
   sample();
  });
  observer.observe(card, { attributes: true, attributeFilter: ['class'] });
 });
 await page.getByRole('button', { name: '标记周末徒步路线已查看' }).click();
 await page.waitForSelector('.empty');
 const dismissal = await page.evaluate(() => window.__dismissSamples);
 writeFileSync('evidence/notification-dismissal.json', JSON.stringify(dismissal, null, 2));
 check('individual dismissal collapses before removal', dismissal.some(v => v.attached && v.height > 0 && v.height < 55 && v.opacity < .95));
 check('dismissing the final result reaches an empty inbox', await page.locator('.result').count() === 0 && (await page.locator('.empty').innerText()).includes('暂时没有'));
 check('no renderer errors', errors.length === 0);
 writeFileSync('evidence/verification.json', JSON.stringify({ checkedAt: new Date().toISOString(), checks, native, rendererErrors: errors, note: 'capturePage screenshots show renderer only; see native CUA capture separately for desktop material. Physical multi-display and Spaces traversal are separate manual checks.' }, null, 2));
 console.log(`${checks.length} checks passed`);
 // Rasterize the exact shipped contour data at the reference's 2x size.
 const paths = JSON.parse(readFileSync('src/capsulePaths.ts', 'utf8').split(' = ')[1].trim().replace(/;$/, ''));
 await page.setContent('<style>body{margin:0;background:black}svg{display:block}</style><div id="glyph"></div>');
 paths.bell = JSON.parse(readFileSync('src/bellPath.ts', 'utf8').split(' = ')[1].trim().replace(/;$/, ''));
 for (const [name, d] of Object.entries(paths)) {
  await page.locator('#glyph').evaluate((e, d) => { e.innerHTML = `<svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" viewBox="0 0 40 40" fill="white"><path fill-rule="evenodd" d="${d}"/></svg>`; }, d);
  await page.locator('svg').screenshot({ path: `evidence/${name}-rendered.png`, scale: 'css', animations: 'disabled' });
 }
} finally { await app.close(); }
