"""L3 reviewer LLM — fresh-context Report-grade verdict on a diff.

Per ADR-0002 § Reviewer contract (lines 715-761) + § Build order Step 9:

- Lives in L3 (``jarvis.decision``), not L4 — Day-1 :class:`LLMClient` is
  L3-owned and L4 cannot import it (D12; ``.importlinter`` enforced).
- Structured JSON output ``{"verdict": "ok"|"fail", "reasons": [...]}``.
- Fresh context: reviewer prompt does NOT include the decision-LLM's
  session history (wrapped in ``with llm_client.fresh_context():``).
- Verdict is Report-grade per spec §8.5 rule 1: the L3 Result Interpreter
  (Step 12) attaches a SEPARATE evidence row at ``level=reported`` and
  never lifts an existing claim to ``level=verified`` on a reviewer
  verdict alone (spec §13.2 I10 — claim ≤ evidence).

Step 9 builds the module standalone. Step 12 wires ``review_diff(...)``
into the L3 ``action.result_observed`` handler and emits
``cost.recorded(kind="reviewer", tokens_in=verdict.tokens_in, ...)``
using the :class:`ReviewerVerdict` fields returned here. This module
does NOT emit ``cost.recorded`` itself — emission is the Step-12
caller's responsibility (companion canary
``test_canary_cost_recorded_emitted_per_llm_call`` exempts
``reviewer.py`` because of this contract).

References:
- ADR-0002 § Reviewer contract (lines 715-761).
- ADR-0002 § Decision D12 (line 245): reviewer at L3, not L4.
- spec.html §8.5 rule 1: agent / LLM self-report = Report-grade source.
- spec.html §13.2 I10: Claim Must Not Exceed Evidence.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from typing import TYPE_CHECKING, Literal

if TYPE_CHECKING:
    from jarvis.decision.llm import LLMClient


@dataclass(frozen=True)
class ReviewerVerdict:
    """Structured verdict returned by :func:`review_diff`.

    Attributes:
        verdict: ``"ok"`` when the reviewer judges the diff matches the
            goal at face value; ``"fail"`` otherwise. Report-grade — the
            downstream Result Interpreter (Step 12) attaches this as a
            separate evidence row and NEVER raises the level beyond
            ``reported`` (spec §8.5 rule 1, §13.2 I10).
        reasons: Tuple of short rationale strings (1-5 entries, each
            ≤ 80 chars). Always populated, even for ``ok`` verdicts; the
            empty tuple is permitted only when the LLM returned an empty
            ``reasons`` list explicitly.
        tokens_in: Prompt tokens consumed by the reviewer chat. Fed into
            the Step-12 ``cost.recorded(kind="reviewer", ...)`` emit.
        tokens_out: Completion tokens generated by the reviewer chat.
            Fed into the Step-12 ``cost.recorded`` emit.
        model: Concrete model id the reviewer ran on (e.g.
            ``"gpt-5.5"``); fed into ``cost.recorded.model`` so reviewer
            spend is attributed per model.
        malformed: ``True`` when the LLM's response was not valid JSON
            and the regex fallback path was used. The Result Interpreter
            uses this to attach a Limitation Claim alongside the verdict
            (the verdict itself is still emitted — we don't drop the
            signal, we just flag its reliability).
        diff_truncated: ``True`` when the diff exceeded
            ``_DIFF_TEXT_CHAR_CAP`` and only its head reached the
            prompt. Surfaced by the Result Interpreter as a Limitation
            flag on the reviewer's evidence row — the verdict was
            formed on partial input.
    """

    verdict: Literal["ok", "fail"]
    reasons: tuple[str, ...]
    tokens_in: int
    tokens_out: int
    model: str
    malformed: bool = False
    diff_truncated: bool = False


# --- reviewer system prompt -------------------------------------------------

# Per ADR-0002 § Reviewer contract: ≤ 1500 chars, English, asks for
# structured JSON output, embeds the spec §13.2 I10 "claim ≤ evidence"
# guardrail. Be terse — the budget is real.
_REVIEWER_SYSTEM_PROMPT = """You are a code reviewer. You receive:

1. A task goal in natural language.
2. A unified git diff a worker produced for that goal.

Determine whether the diff plausibly implements the goal.

Output exactly one JSON object, one line, no prose, no markdown fences:
{"verdict": "ok" | "fail", "reasons": ["reason 1", "reason 2", ...]}

Rules:
- "ok": diff appears to implement the goal at face value.
- "fail": diff is unrelated, contradicts the goal, or is empty when
  work was expected.
- reasons: 1-5 short strings, each <= 80 chars. Be specific — name the
  concrete change (ok) or the concrete mismatch (fail).
- Report-grade verdict (spec 8.5 rule 1): you are reporting judgment,
  not verifying. Only verify_command exit produces verified evidence.
- Claim <= evidence (spec 13.2 I10): when uncertain, return "fail"
  with a reason describing the uncertainty. No hedging.

If the diff is empty:
{"verdict": "fail", "reasons": ["no diff produced"]}

First character of your response must be `{`, last must be `}`.
"""


# Defensive guard: keep the prompt within the ADR-mandated ceiling so
# future edits don't silently blow the budget.
_REVIEWER_SYSTEM_PROMPT_MAX_CHARS = 1500
if len(_REVIEWER_SYSTEM_PROMPT) > _REVIEWER_SYSTEM_PROMPT_MAX_CHARS:  # pragma: no cover
    _msg = (
        f"_REVIEWER_SYSTEM_PROMPT is {len(_REVIEWER_SYSTEM_PROMPT)} chars; "
        f"ADR-0002 caps it at {_REVIEWER_SYSTEM_PROMPT_MAX_CHARS}"
    )
    raise AssertionError(_msg)


# --- review_diff ------------------------------------------------------------

# Cap the diff text fed into the prompt so an unbounded worker output
# cannot blow the reviewer's context window or cost budget. 50K chars is
# ~12.5K tokens — comfortable inside a 200K context with the system
# prompt + goal text + headroom. Truncated diffs still produce a usable
# verdict (the reviewer sees the head of the diff, which usually carries
# enough signal); the alternative — silently failing on large diffs —
# is worse.
_DIFF_TEXT_CHAR_CAP = 50_000


def review_diff(
    *,
    task_goal: str,
    diff_text: str,
    llm_client: LLMClient,
    model: str = "gpt-5.5",
) -> ReviewerVerdict:
    """Run the reviewer LLM on ``diff_text`` against ``task_goal``.

    Wraps the chat call in :meth:`LLMClient.fresh_context` per ADR-0002
    § Reviewer contract so the reviewer prompt does not inherit the
    decision LLM's session history. Asks for structured JSON output;
    falls back to a regex extraction on malformed responses and flags
    the verdict with ``malformed=True`` so callers can attach a
    Limitation Claim.

    Args:
        task_goal: Natural-language goal text (Allen-authored utterance
            that produced the task).
        diff_text: Unified git diff captured after the worker ran
            (Step 8 ``diff_capture``). Truncated to
            ``_DIFF_TEXT_CHAR_CAP`` chars before prompt assembly;
            truncation sets ``diff_truncated`` on the verdict so the
            Result Interpreter can attach a Limitation flag.
        llm_client: L3-owned :class:`LLMClient`. The caller (Step-12
            Result Interpreter) hands in the same client used for
            ``decide()``; the contextmanager is what isolates the call.
        model: Reviewer model id; Day-2 keeps the same backbone as the
            decision LLM (D9). Recorded on the returned
            :class:`ReviewerVerdict` for ``cost.recorded.model``
            attribution by Step 12.

    Returns:
        A :class:`ReviewerVerdict` with ``verdict``, ``reasons``,
        ``tokens_in``, ``tokens_out``, ``model``, ``malformed``,
        ``diff_truncated``.
    """
    # Build a single user message — the reviewer is one-shot, no
    # streaming, no multi-turn. The fence is purely visual separation
    # inside the prompt; the LLM treats it as text.
    diff_truncated = len(diff_text) > _DIFF_TEXT_CHAR_CAP
    diff_for_prompt = diff_text[:_DIFF_TEXT_CHAR_CAP]
    user_text = (
        "---\n"
        "GOAL:\n"
        f"{task_goal}\n"
        "\n"
        "DIFF:\n"
        f"{diff_for_prompt}\n"
        "---\n"
    )

    # Fresh-context wrap: enforced statically by
    # ``test_canary_reviewer_fresh_context``. Day-1 ``chat()`` is
    # stateless so this is a structural marker today — see
    # :meth:`LLMClient.fresh_context` docstring for the rationale.
    with llm_client.fresh_context() as fresh:
        chat_result = fresh.chat(
            messages=[{"role": "user", "content": user_text}],
            system=_REVIEWER_SYSTEM_PROMPT,
            tools=None,
            tool_choice=None,
        )

    # Parse the structured-output response. The system prompt instructs
    # the LLM to emit a single JSON object; if it does, ``json.loads``
    # succeeds and we read ``verdict`` + ``reasons`` directly. Otherwise
    # we fall through to the regex fallback and flag ``malformed=True``.
    raw_text = chat_result.text or ""
    parsed_pair = _try_parse_strict(raw_text)
    if parsed_pair is not None:
        verdict, reasons = parsed_pair
        malformed = False
    else:
        verdict, reasons = _regex_fallback(raw_text)
        malformed = True

    return ReviewerVerdict(
        verdict=verdict,
        reasons=reasons,
        tokens_in=chat_result.tokens_in,
        tokens_out=chat_result.tokens_out,
        model=chat_result.model_used or model,
        malformed=malformed,
        diff_truncated=diff_truncated,
    )


def _try_parse_strict(raw_text: str) -> tuple[Literal["ok", "fail"], tuple[str, ...]] | None:
    """Try to parse a strict ``{"verdict": ..., "reasons": [...]}`` JSON object.

    Returns the ``(verdict, reasons)`` tuple on success, ``None`` on any
    deviation from the expected shape. Returning ``None`` rather than
    raising keeps the call site flat (no internal raise-and-catch) and
    routes the fallback responsibility back to the caller.
    """
    try:
        parsed = json.loads(raw_text)
    except json.JSONDecodeError:
        return None
    if not isinstance(parsed, dict):
        return None
    parsed_verdict = parsed.get("verdict")
    if parsed_verdict not in ("ok", "fail"):
        return None
    raw_reasons = parsed.get("reasons", [])
    if not isinstance(raw_reasons, list):
        return None
    return parsed_verdict, tuple(str(r) for r in raw_reasons)


def _regex_fallback(raw_text: str) -> tuple[Literal["ok", "fail"], tuple[str, ...]]:
    """Pluck a usable verdict out of malformed reviewer text.

    The L3 Result Interpreter (Step 12) will attach a Limitation Claim
    alongside whatever this function returns; we still surface a
    decisive verdict so the downstream evidence ladder has something
    to bind to.
    """
    if re.search(r'"verdict"\s*:\s*"ok"', raw_text, re.IGNORECASE):
        return "ok", ("malformed JSON; extracted via regex",)
    return "fail", ("malformed JSON; reviewer output unparseable",)


__all__ = [
    "ReviewerVerdict",
    "review_diff",
]
